@host = http://localhost:5106/api/Authentication

### Register
# @name register
POST {{host}}/register HTTP/1.1
content-type: application/json

{
    "email": "john.doe@email.com",
    "password": "P@ssword1",
    "role": "User",
    "token":""
}

### Login
@commentId = {{register.response.body.id}}
@username = {{register.response.body.email}}
@password = {{register.response.body.password}}

# @name login
POST {{host}}/login HTTP/1.1
content-type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}"
}

### Login with seed data
# @name loginwithseed (admin)
POST {{host}}/login HTTP/1.1
content-type: application/json

{
  "email": "administrator@localhost",
  "password": "P@ssword1"
}

### Get token
@token = {{login.response.body.token}}

### Delete action
# @name delete
DELETE {{host}}/delete HTTP/1.1
content-type: application/json

{
  "email": "test@test.com",
  "password": "P@ssword1"
}